"""Regenerate rust/crates/sim-core/src/tag.rs: every tag in data/cards.json, plus the tags the code tests that no
card has yet (CODE_ONLY, with the kind of value they would take). Run after re-exporting cards:
    python3 rust/tools/gen_tags.py
"""
import collections, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CODE_ONLY = {'onering': 'Flag', 'narset': 'Flag', 'labyrinth': 'Flag', 'anth': 'Int', 'pstone': 'Flag', 'burn': 'Flag', 'ctrexile': 'Flag', 'drainetb': 'Int', 'dualcaster': 'Flag', 'edictetb': 'Flag', 'evil': 'Flag', 'exiledie': 'Flag', 'newonly': 'Flag', 'pumpall': 'Int', 'selfdmg': 'Int', 'verdict': 'Flag'}


def variant(k):
    v = ''.join(p[:1].upper() + p[1:] for p in re.split(r'[_\-]', k))
    return 'T' + v if v[0].isdigit() else v


def main():
    cards = json.load(open(os.path.join(ROOT, 'data', 'cards.json')))['cards']
    kind = {}
    for c in cards:
        for k, v in c['tags'].items():
            kd = 'Flag' if v is True else ('Int' if re.fullmatch(r'-?\d+', v) else 'Str')
            assert kind.setdefault(k, kd) == kd, k
    for k, kd in CODE_ONLY.items():
        assert kind.setdefault(k, kd) == kd, k
    names = sorted(kind)
    vs = [variant(k) for k in names]
    assert len(set(vs)) == len(vs), [v for v, n in collections.Counter(vs).items() if n > 1]
    out = ['//! Card tags: the engine\'s vocabulary for what a card is and does (see engine.CD in the Python).',
           '//!',
           '//! Generated by rust/tools/gen_tags.py from data/cards.json, plus the tags the code tests that no card has yet',
           '//! (its CODE_ONLY list). Every tag takes one kind of value: a bare flag (`fly`), a number (`pow=7`) or a short',
           '//! string (`rem=exile`). The test in cards.rs checks every tag in the export is known here, with the same kind.',
           '',
           '#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]',
           '#[repr(u16)]',
           'pub enum Tag {']
    out += [f'    {v},' for v in vs]
    out += ['}', '', '#[derive(Debug, Clone, Copy, PartialEq, Eq)]', 'pub enum TagKind {', '    Flag,', '    Int,',
            '    Str,', '}', '', f'pub const TAG_COUNT: usize = {len(names)};', '',
            '/// (tag, its name in the Python code and the export, the kind of value it takes), in `Tag` order.',
            'pub const TAGS: [(Tag, &str, TagKind); TAG_COUNT] = [']
    out += [f'    (Tag::{v}, "{k}", TagKind::{kind[k]}),' for v, k in zip(vs, names)]
    out += ['];', '', 'impl Tag {', '    pub fn name(self) -> &\'static str {', '        TAGS[self as usize].1', '    }', '',
            '    pub fn kind(self) -> TagKind {', '        TAGS[self as usize].2', '    }', '',
            '    /// The tag with this name (a binary search: TAGS is sorted by name).',
            '    pub fn from_name(name: &str) -> Option<Tag> {',
            '        TAGS.binary_search_by(|t| t.1.cmp(name)).ok().map(|i| TAGS[i].0)', '    }', '}', '']
    path = os.path.join(ROOT, 'rust', 'crates', 'sim-core', 'src', 'tag.rs')
    open(path, 'w').write('\n'.join(out))
    print(f'{len(names)} tags ({len(CODE_ONLY)} code-only) -> {path}')


if __name__ == '__main__':
    main()
