//! Card tags: the engine's vocabulary for what a card is and does (see engine.CD in the Python).
//!
//! Generated once from data/cards.json by the M1 script, then kept by hand: a tag the code needs that no card has
//! yet is added here. Every tag takes one kind of value: a bare flag (`fly`), a number (`pow=7`) or a short string
//! (`rem=exile`). The test in cards.rs checks every tag in the export is known here, with the same kind.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
pub enum Tag {
    Adeline,
    Adnaus,
    Aether,
    Agent,
    Alania,
    Alsoart,
    Amt,
    Animist,
    Anthem2,
    Anthemnh,
    Archivist,
    Archon,
    Assault,
    Atraxa,
    Aura,
    Avarice,
    Bahamut,
    Bartist,
    Birgi,
    Bolas,
    Bomb,
    Bounceland,
    Bowmasters,
    Braids,
    Breach,
    Brushoff,
    C,
    Callring,
    Chasm,
    Chromemox,
    Citadel,
    Ck,
    Clamp,
    Cloak,
    Clone,
    Clue,
    Combatspell,
    Conflict,
    Convoke,
    Crackle,
    Crusade,
    Ctr,
    Dawning,
    Deluge,
    Denial,
    Desert,
    Discard1,
    Dork,
    Dragoncaller,
    Drain,
    Draw,
    Drawcre,
    Dredge,
    Dt,
    Enddraw,
    Endraze,
    Eng,
    Eotdraw,
    Erebos,
    Eris,
    Etb,
    Explore,
    F,
    Fable,
    Face,
    Facebreaker,
    Fair,
    Fb,
    Fbdraw,
    Fbgrant,
    Fblife,
    Fbnib,
    Fierce,
    Fill,
    Flail,
    Flash,
    Flute,
    Fly,
    Fon,
    Fotd,
    Free,
    Freecmd,
    Fs,
    Gaintgh,
    Gandalf,
    Garland,
    Gearhulk,
    Gifts,
    Gray,
    Grim,
    Haste,
    Heir,
    Hellkite,
    Helm,
    Human,
    Intuition,
    Ironman,
    Jeska,
    Jin,
    Jinnie,
    Kaervek,
    Kefka,
    Kick,
    Kicker,
    Kiln,
    Kindred,
    Knight,
    Krasis,
    Kylox,
    Labyrinth,
    Landfall2,
    Lantern,
    Lapse,
    Led,
    Leg,
    Lh,
    Lidless,
    Lifelink,
    Loam,
    Lose,
    Losemv,
    Lr,
    Lrt,
    Marchesa,
    Mastery,
    Mauhur,
    Melira,
    Mikaeus,
    Mimic,
    Mirror,
    Misstep,
    Mistrise,
    Mktok,
    Mother,
    Moxd,
    Mv4,
    Mycoloth,
    Mystic,
    Najeela,
    Necro,
    Necromancer,
    Needart3,
    Needsac,
    Nim,
    Noatk,
    Noblock,
    Nodmg,
    Nomax,
    Nonblack,
    Noregen,
    Normgc,
    Nountap,
    Offer,
    Opus3,
    Ozolith,
    Pact,
    Pactpay,
    Pain,
    Panoptic,
    Passage,
    PerCreature,
    PhyU,
    Ping,
    Populate,
    Pow,
    Prepare,
    Primalmight,
    Prodigy,
    Prolif,
    Prolif1,
    Prolifall,
    Prot,
    Pvprolif,
    Rabble,
    Ral,
    Ralzarek,
    Reach,
    Rean,
    Recon,
    Recruit,
    Reenact,
    Rem,
    Remand,
    Remora,
    Rgain,
    Rhys,
    Rhystic,
    Ringtempt,
    Rishkar,
    Rite,
    Rland,
    Rock,
    Rogue,
    Rotw,
    Rsd,
    Rtf,
    Rtok,
    Sac,
    Sacor4,
    Sanar,
    Sauron,
    Seal,
    Shaman,
    Shards,
    SheoA,
    SheoW,
    Skate,
    Snuff,
    Soft,
    Spectacle,
    Spelldraw,
    Spellloot,
    Spelltok,
    Spelltokfly,
    Sphinx,
    Spider,
    Stampede,
    Storm,
    Stormburn,
    Stormmill,
    Suntitan,
    Swampwalk,
    Swan,
    Sword,
    T,
    Tabernacle,
    Tergrid,
    Tgh,
    Tgt,
    Thor,
    Threedreams,
    Titan,
    Tithe,
    Tok,
    Tokatk,
    Tokbig,
    Tokdt,
    Tokfly,
    Toklife,
    Tokp,
    Tokpw,
    Tokup,
    Tokx,
    Tomb,
    Top,
    Trample,
    Treas,
    Tut,
    Tys,
    Unc,
    Undermine,
    Unearth,
    Uprising,
    Vaultping,
    Veyran,
    Vfire,
    Vig,
    Vkitten,
    Vraska,
    Wall,
    Warleader,
    Warmachine,
    Warrior,
    Wipe,
    Wisp,
    Witchking,
    Witness,
    Wizard,
    Workshop,
    Worldtree,
    Wurm,
    Wurmcoil,
    Wurmdrain,
    X,
    Xdrain,
    Xtutor,
    Yawg,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TagKind {
    Flag,
    Int,
    Str,
}

pub const TAG_COUNT: usize = 277;

/// (tag, its name in the Python code and the export, the kind of value it takes), in `Tag` order.
pub const TAGS: [(Tag, &str, TagKind); TAG_COUNT] = [
    (Tag::Adeline, "adeline", TagKind::Flag),
    (Tag::Adnaus, "adnaus", TagKind::Flag),
    (Tag::Aether, "aether", TagKind::Flag),
    (Tag::Agent, "agent", TagKind::Flag),
    (Tag::Alania, "alania", TagKind::Flag),
    (Tag::Alsoart, "alsoart", TagKind::Flag),
    (Tag::Amt, "amt", TagKind::Int),
    (Tag::Animist, "animist", TagKind::Flag),
    (Tag::Anthem2, "anthem2", TagKind::Flag),
    (Tag::Anthemnh, "anthemnh", TagKind::Flag),
    (Tag::Archivist, "archivist", TagKind::Flag),
    (Tag::Archon, "archon", TagKind::Flag),
    (Tag::Assault, "assault", TagKind::Flag),
    (Tag::Atraxa, "atraxa", TagKind::Flag),
    (Tag::Aura, "aura", TagKind::Flag),
    (Tag::Avarice, "avarice", TagKind::Flag),
    (Tag::Bahamut, "bahamut", TagKind::Flag),
    (Tag::Bartist, "bartist", TagKind::Flag),
    (Tag::Birgi, "birgi", TagKind::Flag),
    (Tag::Bolas, "bolas", TagKind::Flag),
    (Tag::Bomb, "bomb", TagKind::Int),
    (Tag::Bounceland, "bounceland", TagKind::Flag),
    (Tag::Bowmasters, "bowmasters", TagKind::Flag),
    (Tag::Braids, "braids", TagKind::Flag),
    (Tag::Breach, "breach", TagKind::Flag),
    (Tag::Brushoff, "brushoff", TagKind::Flag),
    (Tag::C, "c", TagKind::Str),
    (Tag::Callring, "callring", TagKind::Flag),
    (Tag::Chasm, "chasm", TagKind::Flag),
    (Tag::Chromemox, "chromemox", TagKind::Flag),
    (Tag::Citadel, "citadel", TagKind::Flag),
    (Tag::Ck, "ck", TagKind::Flag),
    (Tag::Clamp, "clamp", TagKind::Flag),
    (Tag::Cloak, "cloak", TagKind::Flag),
    (Tag::Clone, "clone", TagKind::Flag),
    (Tag::Clue, "clue", TagKind::Flag),
    (Tag::Combatspell, "combatspell", TagKind::Flag),
    (Tag::Conflict, "conflict", TagKind::Flag),
    (Tag::Convoke, "convoke", TagKind::Flag),
    (Tag::Crackle, "crackle", TagKind::Flag),
    (Tag::Crusade, "crusade", TagKind::Flag),
    (Tag::Ctr, "ctr", TagKind::Str),
    (Tag::Dawning, "dawning", TagKind::Flag),
    (Tag::Deluge, "deluge", TagKind::Flag),
    (Tag::Denial, "denial", TagKind::Flag),
    (Tag::Desert, "desert", TagKind::Flag),
    (Tag::Discard1, "discard1", TagKind::Flag),
    (Tag::Dork, "dork", TagKind::Str),
    (Tag::Dragoncaller, "dragoncaller", TagKind::Flag),
    (Tag::Drain, "drain", TagKind::Flag),
    (Tag::Draw, "draw", TagKind::Int),
    (Tag::Drawcre, "drawcre", TagKind::Flag),
    (Tag::Dredge, "dredge", TagKind::Flag),
    (Tag::Dt, "dt", TagKind::Flag),
    (Tag::Enddraw, "enddraw", TagKind::Flag),
    (Tag::Endraze, "endraze", TagKind::Flag),
    (Tag::Eng, "eng", TagKind::Int),
    (Tag::Eotdraw, "eotdraw", TagKind::Int),
    (Tag::Erebos, "erebos", TagKind::Flag),
    (Tag::Eris, "eris", TagKind::Flag),
    (Tag::Etb, "etb", TagKind::Flag),
    (Tag::Explore, "explore", TagKind::Flag),
    (Tag::F, "f", TagKind::Flag),
    (Tag::Fable, "fable", TagKind::Flag),
    (Tag::Face, "face", TagKind::Flag),
    (Tag::Facebreaker, "facebreaker", TagKind::Flag),
    (Tag::Fair, "fair", TagKind::Flag),
    (Tag::Fb, "fb", TagKind::Str),
    (Tag::Fbdraw, "fbdraw", TagKind::Int),
    (Tag::Fbgrant, "fbgrant", TagKind::Flag),
    (Tag::Fblife, "fblife", TagKind::Int),
    (Tag::Fbnib, "fbnib", TagKind::Flag),
    (Tag::Fierce, "fierce", TagKind::Flag),
    (Tag::Fill, "fill", TagKind::Str),
    (Tag::Flail, "flail", TagKind::Flag),
    (Tag::Flash, "flash", TagKind::Flag),
    (Tag::Flute, "flute", TagKind::Flag),
    (Tag::Fly, "fly", TagKind::Flag),
    (Tag::Fon, "fon", TagKind::Flag),
    (Tag::Fotd, "fotd", TagKind::Flag),
    (Tag::Free, "free", TagKind::Flag),
    (Tag::Freecmd, "freecmd", TagKind::Flag),
    (Tag::Fs, "fs", TagKind::Flag),
    (Tag::Gaintgh, "gaintgh", TagKind::Flag),
    (Tag::Gandalf, "gandalf", TagKind::Flag),
    (Tag::Garland, "garland", TagKind::Flag),
    (Tag::Gearhulk, "gearhulk", TagKind::Flag),
    (Tag::Gifts, "gifts", TagKind::Flag),
    (Tag::Gray, "gray", TagKind::Flag),
    (Tag::Grim, "grim", TagKind::Flag),
    (Tag::Haste, "haste", TagKind::Flag),
    (Tag::Heir, "heir", TagKind::Flag),
    (Tag::Hellkite, "hellkite", TagKind::Flag),
    (Tag::Helm, "helm", TagKind::Flag),
    (Tag::Human, "human", TagKind::Flag),
    (Tag::Intuition, "intuition", TagKind::Flag),
    (Tag::Ironman, "ironman", TagKind::Flag),
    (Tag::Jeska, "jeska", TagKind::Flag),
    (Tag::Jin, "jin", TagKind::Flag),
    (Tag::Jinnie, "jinnie", TagKind::Flag),
    (Tag::Kaervek, "kaervek", TagKind::Flag),
    (Tag::Kefka, "kefka", TagKind::Flag),
    (Tag::Kick, "kick", TagKind::Int),
    (Tag::Kicker, "kicker", TagKind::Flag),
    (Tag::Kiln, "kiln", TagKind::Flag),
    (Tag::Kindred, "kindred", TagKind::Flag),
    (Tag::Knight, "knight", TagKind::Flag),
    (Tag::Krasis, "krasis", TagKind::Flag),
    (Tag::Kylox, "kylox", TagKind::Flag),
    (Tag::Labyrinth, "labyrinth", TagKind::Flag),
    (Tag::Landfall2, "landfall2", TagKind::Flag),
    (Tag::Lantern, "lantern", TagKind::Flag),
    (Tag::Lapse, "lapse", TagKind::Flag),
    (Tag::Led, "led", TagKind::Flag),
    (Tag::Leg, "leg", TagKind::Flag),
    (Tag::Lh, "lh", TagKind::Int),
    (Tag::Lidless, "lidless", TagKind::Flag),
    (Tag::Lifelink, "lifelink", TagKind::Flag),
    (Tag::Loam, "loam", TagKind::Flag),
    (Tag::Lose, "lose", TagKind::Int),
    (Tag::Losemv, "losemv", TagKind::Flag),
    (Tag::Lr, "lr", TagKind::Int),
    (Tag::Lrt, "lrt", TagKind::Flag),
    (Tag::Marchesa, "marchesa", TagKind::Flag),
    (Tag::Mastery, "mastery", TagKind::Flag),
    (Tag::Mauhur, "mauhur", TagKind::Flag),
    (Tag::Melira, "melira", TagKind::Flag),
    (Tag::Mikaeus, "mikaeus", TagKind::Flag),
    (Tag::Mimic, "mimic", TagKind::Flag),
    (Tag::Mirror, "mirror", TagKind::Flag),
    (Tag::Misstep, "misstep", TagKind::Flag),
    (Tag::Mistrise, "mistrise", TagKind::Flag),
    (Tag::Mktok, "mktok", TagKind::Str),
    (Tag::Mother, "mother", TagKind::Flag),
    (Tag::Moxd, "moxd", TagKind::Flag),
    (Tag::Mv4, "mv4", TagKind::Flag),
    (Tag::Mycoloth, "mycoloth", TagKind::Flag),
    (Tag::Mystic, "mystic", TagKind::Flag),
    (Tag::Najeela, "najeela", TagKind::Flag),
    (Tag::Necro, "necro", TagKind::Flag),
    (Tag::Necromancer, "necromancer", TagKind::Flag),
    (Tag::Needart3, "needart3", TagKind::Flag),
    (Tag::Needsac, "needsac", TagKind::Flag),
    (Tag::Nim, "nim", TagKind::Flag),
    (Tag::Noatk, "noatk", TagKind::Flag),
    (Tag::Noblock, "noblock", TagKind::Flag),
    (Tag::Nodmg, "nodmg", TagKind::Flag),
    (Tag::Nomax, "nomax", TagKind::Flag),
    (Tag::Nonblack, "nonblack", TagKind::Flag),
    (Tag::Noregen, "noregen", TagKind::Flag),
    (Tag::Normgc, "normgc", TagKind::Flag),
    (Tag::Nountap, "nountap", TagKind::Flag),
    (Tag::Offer, "offer", TagKind::Flag),
    (Tag::Opus3, "opus3", TagKind::Flag),
    (Tag::Ozolith, "ozolith", TagKind::Flag),
    (Tag::Pact, "pact", TagKind::Flag),
    (Tag::Pactpay, "pactpay", TagKind::Str),
    (Tag::Pain, "pain", TagKind::Flag),
    (Tag::Panoptic, "panoptic", TagKind::Flag),
    (Tag::Passage, "passage", TagKind::Flag),
    (Tag::PerCreature, "perCreature", TagKind::Flag),
    (Tag::PhyU, "phyU", TagKind::Flag),
    (Tag::Ping, "ping", TagKind::Int),
    (Tag::Populate, "populate", TagKind::Flag),
    (Tag::Pow, "pow", TagKind::Int),
    (Tag::Prepare, "prepare", TagKind::Flag),
    (Tag::Primalmight, "primalmight", TagKind::Flag),
    (Tag::Prodigy, "prodigy", TagKind::Flag),
    (Tag::Prolif, "prolif", TagKind::Flag),
    (Tag::Prolif1, "prolif1", TagKind::Flag),
    (Tag::Prolifall, "prolifall", TagKind::Flag),
    (Tag::Prot, "prot", TagKind::Str),
    (Tag::Pvprolif, "pvprolif", TagKind::Flag),
    (Tag::Rabble, "rabble", TagKind::Flag),
    (Tag::Ral, "ral", TagKind::Flag),
    (Tag::Ralzarek, "ralzarek", TagKind::Flag),
    (Tag::Reach, "reach", TagKind::Flag),
    (Tag::Rean, "rean", TagKind::Str),
    (Tag::Recon, "recon", TagKind::Flag),
    (Tag::Recruit, "recruit", TagKind::Flag),
    (Tag::Reenact, "reenact", TagKind::Flag),
    (Tag::Rem, "rem", TagKind::Str),
    (Tag::Remand, "remand", TagKind::Flag),
    (Tag::Remora, "remora", TagKind::Flag),
    (Tag::Rgain, "rgain", TagKind::Flag),
    (Tag::Rhys, "rhys", TagKind::Flag),
    (Tag::Rhystic, "rhystic", TagKind::Flag),
    (Tag::Ringtempt, "ringtempt", TagKind::Flag),
    (Tag::Rishkar, "rishkar", TagKind::Flag),
    (Tag::Rite, "rite", TagKind::Flag),
    (Tag::Rland, "rland", TagKind::Flag),
    (Tag::Rock, "rock", TagKind::Str),
    (Tag::Rogue, "rogue", TagKind::Flag),
    (Tag::Rotw, "rotw", TagKind::Flag),
    (Tag::Rsd, "rsd", TagKind::Flag),
    (Tag::Rtf, "rtf", TagKind::Flag),
    (Tag::Rtok, "rtok", TagKind::Int),
    (Tag::Sac, "sac", TagKind::Flag),
    (Tag::Sacor4, "sacor4", TagKind::Flag),
    (Tag::Sanar, "sanar", TagKind::Flag),
    (Tag::Sauron, "sauron", TagKind::Flag),
    (Tag::Seal, "seal", TagKind::Flag),
    (Tag::Shaman, "shaman", TagKind::Flag),
    (Tag::Shards, "shards", TagKind::Flag),
    (Tag::SheoA, "sheoA", TagKind::Flag),
    (Tag::SheoW, "sheoW", TagKind::Flag),
    (Tag::Skate, "skate", TagKind::Flag),
    (Tag::Snuff, "snuff", TagKind::Flag),
    (Tag::Soft, "soft", TagKind::Int),
    (Tag::Spectacle, "spectacle", TagKind::Flag),
    (Tag::Spelldraw, "spelldraw", TagKind::Flag),
    (Tag::Spellloot, "spellloot", TagKind::Flag),
    (Tag::Spelltok, "spelltok", TagKind::Int),
    (Tag::Spelltokfly, "spelltokfly", TagKind::Flag),
    (Tag::Sphinx, "sphinx", TagKind::Flag),
    (Tag::Spider, "spider", TagKind::Flag),
    (Tag::Stampede, "stampede", TagKind::Flag),
    (Tag::Storm, "storm", TagKind::Flag),
    (Tag::Stormburn, "stormburn", TagKind::Flag),
    (Tag::Stormmill, "stormmill", TagKind::Flag),
    (Tag::Suntitan, "suntitan", TagKind::Flag),
    (Tag::Swampwalk, "swampwalk", TagKind::Flag),
    (Tag::Swan, "swan", TagKind::Flag),
    (Tag::Sword, "sword", TagKind::Flag),
    (Tag::T, "t", TagKind::Flag),
    (Tag::Tabernacle, "tabernacle", TagKind::Flag),
    (Tag::Tergrid, "tergrid", TagKind::Flag),
    (Tag::Tgh, "tgh", TagKind::Int),
    (Tag::Tgt, "tgt", TagKind::Str),
    (Tag::Thor, "thor", TagKind::Flag),
    (Tag::Threedreams, "threedreams", TagKind::Flag),
    (Tag::Titan, "titan", TagKind::Flag),
    (Tag::Tithe, "tithe", TagKind::Flag),
    (Tag::Tok, "tok", TagKind::Int),
    (Tag::Tokatk, "tokatk", TagKind::Int),
    (Tag::Tokbig, "tokbig", TagKind::Flag),
    (Tag::Tokdt, "tokdt", TagKind::Flag),
    (Tag::Tokfly, "tokfly", TagKind::Flag),
    (Tag::Toklife, "toklife", TagKind::Flag),
    (Tag::Tokp, "tokp", TagKind::Int),
    (Tag::Tokpw, "tokpw", TagKind::Flag),
    (Tag::Tokup, "tokup", TagKind::Int),
    (Tag::Tokx, "tokx", TagKind::Flag),
    (Tag::Tomb, "tomb", TagKind::Flag),
    (Tag::Top, "top", TagKind::Flag),
    (Tag::Trample, "trample", TagKind::Flag),
    (Tag::Treas, "treas", TagKind::Int),
    (Tag::Tut, "tut", TagKind::Str),
    (Tag::Tys, "tys", TagKind::Flag),
    (Tag::Unc, "unc", TagKind::Flag),
    (Tag::Undermine, "undermine", TagKind::Flag),
    (Tag::Unearth, "unearth", TagKind::Flag),
    (Tag::Uprising, "uprising", TagKind::Flag),
    (Tag::Vaultping, "vaultping", TagKind::Flag),
    (Tag::Veyran, "veyran", TagKind::Flag),
    (Tag::Vfire, "vfire", TagKind::Flag),
    (Tag::Vig, "vig", TagKind::Flag),
    (Tag::Vkitten, "vkitten", TagKind::Flag),
    (Tag::Vraska, "vraska", TagKind::Flag),
    (Tag::Wall, "wall", TagKind::Flag),
    (Tag::Warleader, "warleader", TagKind::Flag),
    (Tag::Warmachine, "warmachine", TagKind::Flag),
    (Tag::Warrior, "warrior", TagKind::Flag),
    (Tag::Wipe, "wipe", TagKind::Str),
    (Tag::Wisp, "wisp", TagKind::Flag),
    (Tag::Witchking, "witchking", TagKind::Flag),
    (Tag::Witness, "witness", TagKind::Flag),
    (Tag::Wizard, "wizard", TagKind::Flag),
    (Tag::Workshop, "workshop", TagKind::Flag),
    (Tag::Worldtree, "worldtree", TagKind::Flag),
    (Tag::Wurm, "wurm", TagKind::Flag),
    (Tag::Wurmcoil, "wurmcoil", TagKind::Flag),
    (Tag::Wurmdrain, "wurmdrain", TagKind::Flag),
    (Tag::X, "x", TagKind::Flag),
    (Tag::Xdrain, "xdrain", TagKind::Flag),
    (Tag::Xtutor, "xtutor", TagKind::Flag),
    (Tag::Yawg, "yawg", TagKind::Flag),
];

impl Tag {
    pub fn name(self) -> &'static str {
        TAGS[self as usize].1
    }

    pub fn kind(self) -> TagKind {
        TAGS[self as usize].2
    }

    /// The tag with this name (a binary search: TAGS is sorted by name).
    pub fn from_name(name: &str) -> Option<Tag> {
        TAGS.binary_search_by(|t| t.1.cmp(name)).ok().map(|i| TAGS[i].0)
    }
}
